project:
  type: website

website:
  title: omeka2dsp
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: https://Stadt-Geschichte-Basel.github.io/omeka2dsp/
  repo-url: https://github.com/Stadt-Geschichte-Basel/omeka2dsp/
  issue-url: https://github.com/Stadt-Geschichte-Basel/omeka2dsp/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: android-chrome-512x512.png
    logo-alt: ''
    title: omeka2dsp
    tools:
      - icon: github
        url: https://github.com/Stadt-Geschichte-Basel/omeka2dsp/
    left:
      - text: Home
        href: index.qmd
      - text: Documentation
        menu:
          - text: Overview
            href: documentation.qmd
          - text: '---'
          - text: Architecture
            href: architecture.qmd
          - text: Workflows
            href: workflows.qmd
          - text: API Reference
            href: api.qmd
          - text: '---'
          - text: Installation
            href: installation.qmd
          - text: Configuration
            href: configuration.qmd
          - text: Usage
            href: usage.qmd
          - text: Development
            href: development.qmd
          - text: Troubleshooting
            href: troubleshooting.qmd
      - text: Report
        href: report.md

  sidebar:
    contents:
      - section: omeka2dsp
        href: index.qmd
        contents:
          - text: Changelog
            href: CHANGELOG.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: Contributing
            href: CONTRIBUTING.md
          - text: License (Data)
            href: LICENSE-CCBY.md
          - text: License (Code)
            href: LICENSE-AGPL.md
          - text: Security
            href: SECURITY.md
      - section: Documentation
        contents:
          - text: Overview
            href: documentation.qmd
          - text: System Architecture
            href: architecture.qmd
          - text: Data Workflows
            href: workflows.qmd
          - text: API Reference
            href: api.qmd
      - section: Guides
        contents:
          - text: Installation & Setup
            href: installation.qmd
          - text: Configuration
            href: configuration.qmd
          - text: Usage Guide
            href: usage.qmd
          - text: Development Guide
            href: development.qmd
          - text: Troubleshooting
            href: troubleshooting.qmd
      - href: report.md
        contents: project-management/*

format:
  html:
    toc: true
    theme:
      - brand
      - cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap

freeze: true

editor: visual
