contact_links:
  - name: Are you looking for documentation on sgb_data?
    url: https://koilebeit.github.io/sgb_data
    about: Please see the documentation for sgb_data on its GitHub Pages page.
  - name: Do want to discuss sgb_data with the community?
    url: https://github.com/koilebeit/sgb_data/discussions
    about: Please see the discussions page for sgb_data.
blank_issues_enabled: true
